require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MacOSExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'MacOSExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  post_install do |installer|
    # flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |build_configuration|
      build_configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'No'
    end
  end
end

target 'MacOSExample-tvOS' do
  # Pods for MacOSExample-tvOS

  target 'MacOSExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
